In [1]:
import numpy as np
import torch
import os



In [4]:
from PIL import Image


In [3]:
import matplotlib.pyplot as plt

In [5]:
im_path = "/media/ubuntu/New Volume/jay/fundus_images/archive/REFUGE/val/Masks/V0001.png"
img = torch.as_tensor(np.array(Image.open(im_path).convert("RGB")))


In [8]:
np.unique(img[:,:,0])

array([0, 1, 2], dtype=uint8)

In [3]:
model_dict_path = "./eval/cholec8k/svd_shiftscale_cholec_tal_focal075_1e-4.pth"
model_dict = torch.load(model_dict_path, map_location='cpu')

In [4]:
keys = list(model_dict.keys())

In [5]:
keys

['sam_encoder.pos_embed',
 'sam_encoder.patch_embed.proj.weight',
 'sam_encoder.patch_embed.proj.bias',
 'sam_encoder.blocks.0.norm1.weight',
 'sam_encoder.blocks.0.norm1.bias',
 'sam_encoder.blocks.0.attn.qkv.weight',
 'sam_encoder.blocks.0.attn.qkv.bias',
 'sam_encoder.blocks.0.attn.qkv.trainable_scale',
 'sam_encoder.blocks.0.attn.qkv.trainable_shift',
 'sam_encoder.blocks.0.attn.proj.weight',
 'sam_encoder.blocks.0.attn.proj.bias',
 'sam_encoder.blocks.0.attn.proj.trainable_scale',
 'sam_encoder.blocks.0.attn.proj.trainable_shift',
 'sam_encoder.blocks.0.norm2.weight',
 'sam_encoder.blocks.0.norm2.bias',
 'sam_encoder.blocks.0.mlp.lin1.weight',
 'sam_encoder.blocks.0.mlp.lin1.bias',
 'sam_encoder.blocks.0.mlp.lin1.trainable_scale',
 'sam_encoder.blocks.0.mlp.lin1.trainable_shift',
 'sam_encoder.blocks.0.mlp.lin2.weight',
 'sam_encoder.blocks.0.mlp.lin2.bias',
 'sam_encoder.blocks.0.mlp.lin2.trainable_scale',
 'sam_encoder.blocks.0.mlp.lin2.trainable_shift',
 'sam_encoder.blocks.1.n

In [6]:
def basic_stats(key):
    print('min: ', model_dict[key].min())
    print('max: ', model_dict[key].max())
    print('mean: ', model_dict[key].mean())
    print('norm: ', np.linalg.norm(model_dict[key].numpy()))



In [8]:
basic_stats('mask_decoder.transformer.layers.0.mlp.lin1.trainable_shift')

min:  tensor(0.)
max:  tensor(0.)
mean:  tensor(0.)
norm:  0.0


In [10]:
a = "a.b.c.d"
a.replace("c","e")
a

'a.b.c.d'

In [7]:
import nibabel as nib
import numpy as np
import os

In [18]:
os.listdir('/media/ubuntu/New Volume/jay/BTCV/train_npz')[18:50]

['case0005_slice018.npz',
 'case0027_slice043.npz',
 'case0027_slice044.npz',
 'case0027_slice045.npz',
 'case0027_slice046.npz',
 'case0027_slice047.npz',
 'case0027_slice048.npz',
 'case0027_slice049.npz',
 'case0027_slice050.npz',
 'case0027_slice051.npz',
 'case0027_slice052.npz',
 'case0027_slice053.npz',
 'case0027_slice054.npz',
 'case0027_slice055.npz',
 'case0027_slice056.npz',
 'case0027_slice057.npz',
 'case0027_slice058.npz',
 'case0027_slice059.npz',
 'case0027_slice060.npz',
 'case0027_slice061.npz',
 'case0027_slice062.npz',
 'case0027_slice063.npz',
 'case0027_slice064.npz',
 'case0027_slice065.npz',
 'case0027_slice066.npz',
 'case0027_slice067.npz',
 'case0027_slice068.npz',
 'case0010_slice080.npz',
 'case0010_slice081.npz',
 'case0010_slice082.npz',
 'case0010_slice083.npz',
 'case0010_slice084.npz']

In [9]:
# im = nib.load('/media/ubuntu/New Volume/jay/LiTS/images/1.nii')
im = np.load('/media/ubuntu/New Volume/jay/BTCV/train_npz/case0005_slice000.npz')

In [16]:
list(im.keys())
print(im['image'].shape)

(512, 512)


In [1]:
import torch

In [2]:
a = torch.Tensor([
    [1,0,0,0,1],
    [0,0,0,1,1]
])
torch.where(a==1)

(tensor([0, 0, 1, 1]), tensor([0, 4, 3, 4]))

In [6]:
a = [[torch.tensor(315), torch.tensor(581)], [torch.tensor(339), torch.tensor(340)]]
print(torch.Tensor(a))

tensor([[315., 581.],
        [339., 340.]])
